### ISSUE TITLE
Default password for "louder-asp" access point?

### ISSUE THREAD

**Issue by TommySharpNZ** [sonocotta/esp32-audio-dock#10]
I purchased some of these from Tindie pre-loaded with Squeezelite, but I can't seem to find a definitive mention of what the AP password is?

**Comment by anabolyc** [comment]
It is `sqeezelite`

**Comment by TommySharpNZ** [comment]
Hmmmm okaye "squeezelite" seems to be the password :-) Needs the "u"...
