### ISSUE TITLE
louder esp snapcast audio

### ISSUE THREAD

**Issue by developsad** [sonocotta/esp32-audio-dock#11]
Hi. I installed snapcast on my louder esp.
Its working but there is some strange audio behavior.
It sounds like floating sound or lossy samle rate. I can hear it mainly on hights where they are clear and then they become dull. I tried with dsp, without dsp.
The board is ok because when i had the squeezelite installed there was no such behavior

**Comment by anabolyc** [comment]
Hey @developsad . I'm checking with upstream developers if that's a known issue or perhaps something that is a work in progress. So far I didn't witness myself this behavior, so I'm not sure what it is caused by

**Comment by anabolyc** [comment]
Fixed by #12
